#
# Module manifest for module 'SpotifyModule'
#
# Generated by: Pierre Chretien
#
# Generated on: 2024-09-28
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'SpotifyModule.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'bf686ca9-a916-4361-b393-b274f7f70fdb'

    # Author of this module
    Author = 'Pierre Chretien'

    # Company or vendor of this module
    CompanyName = 'goldfeesh'

    # Copyright statement for this module
    Copyright = '(c) Pierre Chretien. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'PowerShell module to interact with Spotify API'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Functions to export from this module, defined as an array
    FunctionsToExport = @(
        'Initialize-SpotifyClient'
        'Invoke-WebServer',
        'Open-AuthorizationUrl',
        'Get-AccessToken',
        'Get-RefreshToken',
        'Get-CurrentSong'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @('SpotifyModule\SpotifyClient.psm1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
